site_name: Nestor
repo_url: "https://github.com/usnistgov/nestor"
site_description: "Quantifying tacit human knowledge for Smart Manufacturing Maintenance, for maintnenance-based investigatory analysis"
site_author: "Thurston Sexton"
nav: 
  - Home: "README.md"
  - License: "LICENSE.md"
  - Getting Started:
      - "Install & Setup": "getting-started.md"
      - Motivation: "motivation.md"
      - Workflow: "workflow.md"
  - User Interfaces: "gui-links.md"
  - Examples:
      "Survival Analysis": "examples/survival-analysis/survival-analysis.md"
  - API Reference:
      - settings: "nestor/settings.md"
      - keyword: "nestor/keyword.md"
      # - tagtrees: "nestor/tagtrees.md"
      - datasets: "nestor/datasets.md"
theme:
  name: "material"
  favicon: "media/favicon.png"
  logo: "media/icon.png"
  palette:
    primary: "blue grey"
    accent : "orange"
plugins:
  - search
  - mkdocstrings:
      watch:
        - nestor
  # - pdf-export:
      # combined: true
  - with-pdf:
      # render_js: true
      cover: true
      cover_subtitle: "Toolkit Documentation"
      toc_level: 2
      ordered_chapter_level: 2
      enabled_if_env: ENABLE_PDF_EXPORT
      output_path: 'pdf/nestor-documentation.pdf'
      # exclude_pages:
      #   - 'about/templates/'
  - mermaid2
  - bibtex:
      bib_file: "docs/biblio.bib"
      cite_style: "pandoc"
extra_css:
  - "https://pages.nist.gov/nist-header-footer/css/nist-combined.css"
extra_javascript:
  - "https://unpkg.com/mermaid/dist/mermaid.min.js"
  - "https://pages.nist.gov/nist-header-footer/js/jquery-1.9.0.min.js"
  - "https://pages.nist.gov/nist-header-footer/js/nist-header-footer.js"
site_dir: "public"
markdown_extensions:
  - footnotes
  - pymdownx.superfences
