# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'n-grame_ui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.vertOneGrameTokenLayout = QtWidgets.QVBoxLayout()
        self.vertOneGrameTokenLayout.setObjectName("vertCheckBoxLayout")
        self.vlayout_one_grame_tokens = QtWidgets.QGridLayout()
        self.vlayout_one_grame_tokens.setObjectName("vlayout_one_grame_tokens")
        self.vertOneGrameTokenLayout.addLayout(self.vlayout_one_grame_tokens)
        self.gridLayout.addLayout(self.vertOneGrameTokenLayout, 1, 3, 1, 1)
        self.vocabTableWidget = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vocabTableWidget.sizePolicy().hasHeightForWidth())
        self.vocabTableWidget.setSizePolicy(sizePolicy)
        self.vocabTableWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.vocabTableWidget.setEditTriggers(QtWidgets.QAbstractItemView.EditKeyPressed)
        self.vocabTableWidget.setTabKeyNavigation(False)
        self.vocabTableWidget.setDragDropOverwriteMode(False)
        self.vocabTableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.vocabTableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.vocabTableWidget.setObjectName("vocabTableWidget")
        self.vocabTableWidget.setColumnCount(0)
        self.vocabTableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.vocabTableWidget, 1, 2, 1, 1)
        self.headLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.headLabel.sizePolicy().hasHeightForWidth())
        self.headLabel.setSizePolicy(sizePolicy)
        self.headLabel.setObjectName("headLabel")
        self.gridLayout.addWidget(self.headLabel, 0, 2, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.aliasLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aliasLabel.sizePolicy().hasHeightForWidth())
        self.aliasLabel.setSizePolicy(sizePolicy)
        self.aliasLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.aliasLabel.setObjectName("aliasLabel")
        self.verticalLayout_2.addWidget(self.aliasLabel)
        self.aliasEdit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aliasEdit.sizePolicy().hasHeightForWidth())
        self.aliasEdit.setSizePolicy(sizePolicy)
        self.aliasEdit.setClearButtonEnabled(False)
        self.aliasEdit.setObjectName("aliasEdit")
        self.verticalLayout_2.addWidget(self.aliasEdit)
        self.itemItemRadioB = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemItemRadioB.sizePolicy().hasHeightForWidth())
        self.itemItemRadioB.setSizePolicy(sizePolicy)
        self.itemItemRadioB.setObjectName("itemItemRadioB")
        self.clfButtonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.clfButtonGroup.setObjectName("clfButtonGroup")
        self.clfButtonGroup.addButton(self.itemItemRadioB)
        self.verticalLayout_2.addWidget(self.itemItemRadioB)
        self.problemItemRadioB = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.problemItemRadioB.sizePolicy().hasHeightForWidth())
        self.problemItemRadioB.setSizePolicy(sizePolicy)
        self.problemItemRadioB.setObjectName("problemItemRadioB")
        self.clfButtonGroup.addButton(self.problemItemRadioB)
        self.verticalLayout_2.addWidget(self.problemItemRadioB)
        self.solutionItemRadioB = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.solutionItemRadioB.sizePolicy().hasHeightForWidth())
        self.solutionItemRadioB.setSizePolicy(sizePolicy)
        self.solutionItemRadioB.setObjectName("solutionItemRadioB")
        self.clfButtonGroup.addButton(self.solutionItemRadioB)
        self.verticalLayout_2.addWidget(self.solutionItemRadioB)
        self.unknownRadioB = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.unknownRadioB.sizePolicy().hasHeightForWidth())
        self.unknownRadioB.setSizePolicy(sizePolicy)
        self.unknownRadioB.setObjectName("unknownRadioB")
        self.clfButtonGroup.addButton(self.unknownRadioB)
        self.verticalLayout_2.addWidget(self.unknownRadioB)
        self.stopwordRadioB = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopwordRadioB.sizePolicy().hasHeightForWidth())
        self.stopwordRadioB.setSizePolicy(sizePolicy)
        self.stopwordRadioB.setObjectName("stopwordRadioB")
        self.clfButtonGroup.addButton(self.stopwordRadioB)
        self.verticalLayout_2.addWidget(self.stopwordRadioB)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem)
        self.unsetButton = QtWidgets.QRadioButton(self.centralwidget)
        self.unsetButton.setObjectName("unsetButton")
        self.clfButtonGroup.addButton(self.unsetButton)
        self.verticalLayout_2.addWidget(self.unsetButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.notesTextEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.notesTextEdit.setObjectName("notesTextEdit")
        self.verticalLayout_2.addWidget(self.notesTextEdit)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.updateButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.updateButton.sizePolicy().hasHeightForWidth())
        self.updateButton.setSizePolicy(sizePolicy)
        self.updateButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.updateButton.setObjectName("updateButton")
        self.verticalLayout_2.addWidget(self.updateButton)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 5, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 3, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 4, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tag Annotator v0.0.2"))
        self.headLabel.setText(_translate("MainWindow", "Beta Tag Annotation"))
        self.label_2.setText(_translate("MainWindow", "Entry Editor"))
        self.aliasLabel.setText(_translate("MainWindow", "Preferred Alias"))
        self.itemItemRadioB.setText(_translate("MainWindow", "Item"))
        self.stopwordRadioB.setText(_translate("MainWindow", "Stop-word"))
        self.problemItemRadioB.setText(_translate("MainWindow", "Problem Item"))
        self.solutionItemRadioB.setText(_translate("MainWindow", "Solution Item"))
        self.unknownRadioB.setText(_translate("MainWindow", "Unknown"))
        self.unsetButton.setText(_translate("MainWindow", "not yet classified"))
        self.label.setText(_translate("MainWindow", "Notes"))
        self.updateButton.setText(_translate("MainWindow", "Update"))
        self.updateButton.setShortcut(_translate("MainWindow", "Return"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
