#!/usr/bin/env python
#
# This file is part of Nestor. It is subject to the license terms in the file
# LICENSE.rst found in the top-level directory of this distribution.

from nestor.dash import app
import os

if __name__ == '__main__':
    app.secret_key = os.urandom(24)
    app.run(debug=True)